### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AIisaweapon** [JosuaLimbu/npr-tesseract#1]
![image](https://github.com/JosuaLimbu/npr-tesseract/assets/172877079/f3c0122b-22d1-4871-ac62-0b641606a5fc)
`\npr-tesseract> & C:/Users//miniconda3/envs/myenv/python.exe c:/Users/Xiu/Downloads/dev/npr-tesseract/number_plate.py
[ERROR:0@0.418] global obsensor_uvc_stream_channel.cpp:158 cv::obsensor::getStreamChannelGroup Camera index out of range
Traceback (most recent call last):
  File "c:\Users\Xiu\Downloads\dev\npr-tesseract\number_plate.py", line 39, in <module>
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'`

**Comment by AIisaweapon** [comment]
Ok i have to install a fake webcam to use it .

Ty.

**Comment by JosuaLimbu** [comment]
Have you succeeded in resolving the error? if on my laptop it should work using python version 3.10.11

**Comment by AIisaweapon** [comment]
> Have you succeeded in resolving the error? if on my laptop it should work using python version 3.10.11

Nop :(

Do you have webcam on your computer ?

Tried with fake webcam usb drivers but another error.

**Comment by AIisaweapon** [comment]
Tested with python 3,11 (like your screenshot) on mac and windows

**Comment by JosuaLimbu** [comment]
> > Have you succeeded in resolving the error? if on my laptop it should work using python version 3.10.11
> 
> Nop :(
> 
> Do you have webcam on your computer ?
> 
> Tried with fake webcam usb drivers but another error.

No, I am using the built-in webcam of my Windows laptop. Or you can try this code to open OpenCV on your laptop; if it doesn't work, there might be an issue with your laptop's webcam driver.

import cv2

cap = cv2.VideoCapture(0)

if not cap.isOpened():
    print("Error: Tidak dapat membuka kamera")
else:
    while True:
        ret, frame = cap.read()
        
        if not ret:
            print("Error: Tidak dapat membaca frame")
            break
        
        cv2.imshow('Camera', frame)
        
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()
